version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql.railway.internal
      DB_PORT: 3306
      DB_DATABASE: railway
      DB_USERNAME: root
      DB_PASSWORD: HngsBIyzrSXiawUGREdOeJKWiqvprMJw
    entrypoint: ["/var/www/entrypoint.sh"]
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: railway
      MYSQL_ROOT_PASSWORD: HngsBIyzrSXiawUGREdOeJKWiqvprMJw
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
